/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Text } from "@react-three/drei";

const Model2 = (props) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("/modal2.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Title"
          position={[-0.47, -0.83, 0.28]}
          rotation={[1.56, 0, 0]}
          scale={0.28}
        />
        <mesh
          name="Bottle"
          geometry={nodes.Bottle.geometry}
          material={materials.Glass}
          scale={[0.72, 1, 0.26]}
        >
          <mesh
            name="BezierCurve"
            geometry={nodes.BezierCurve.geometry}
            material={materials["Material.002"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.38, 3.84, 1]}
          />
          <mesh
            name="Circle"
            geometry={nodes.Circle.geometry}
            material={materials["Fine Gold"]}
            position={[0, 1.03, 0]}
            scale={[1.38, 1, 3.84]}
          />
          <mesh
            name="Perfume"
            geometry={nodes.Perfume.geometry}
            material={materials["Water realistic"]}
            scale={[0.99, 1, 0.97]}
          />
          <mesh position={[0, -0.3, 1.1]}>
            <Text
              color="#FFFFFF"
              fontSize={0.26}
              maxWidth={20}
              lineHeight={1}
              letterSpacing={0}
              textAlign="right"
              text={props.text.front}
              font="https://fonts.gstatic.com/s/raleway/v14/1Ptrg8zYS_SKggPNwK4vaqI.woff"
              anchorX="center"
              anchorY="middle"
            >
              {props.text.front}
            </Text>
          </mesh>
        </mesh>
      </group>
    </group>
  );
};

export default Model2;

useGLTF.preload("/modal2.glb");
